#!/usr/bin/env python



def options(opt):
    pass

def configure(opt):
    pass

def build(bld):
    bld.program( source = '''
        CodeEditor.cxx
        Fl_Function_Type.cxx
        Fl_Group_Type.cxx
        Fl_Menu_Type.cxx
        Fl_Type.cxx
        Fl_Widget_Type.cxx
        Fl_Window_Type.cxx
        Fluid_Image.cxx
        about_panel.cxx
        align_widget.cxx
        alignment_panel.cxx
        code.cxx
        factory.cxx
        file.cxx
        fluid.cxx
        function_panel.cxx
        template_panel.cxx
        undo.cxx
        widget_panel.cxx
''',
                 target='ntk-fluid',
                 includes = [ '.', '../' ],
                 use = [ 'ntk_images_shared', 'ntk_shared' ],
                 install_path = '${BINDIR}' )
    
