#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):

    lib_source = '''
png.c
pngerror.c
pngget.c
pngmem.c
pngpread.c
pngread.c
pngrio.c
pngrtran.c
pngrutil.c
pngset.c
pngtrans.c
pngwio.c
pngwrite.c
pngwtran.c
pngwutil.c
'''

    bld.stlib( source = lib_source,
               cflags = [ '-fPIC' ],
               cxxflags = [ '-fPIC' ],
               target = 'ntk_png',
               includes = ['.' ],
               install_path = None )
