#!/usr/bin/env python

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):

    lib_source = '''
adler32.c
compress.c
crc32.c
deflate.c
gzclose.c
gzlib.c
gzread.c
gzwrite.c
infback.c
inffast.c
inflate.c
inftrees.c
trees.c
uncompr.c
zutil.c
'''
    bld.stlib( source = lib_source,
               cflags = [ '-fPIC' ],
               cxxflags = [ '-fPIC' ],
               target = 'ntk_zlib',
               includes = ['.' ],
               install_path = None )
